image: node:6

#Installing node dependency by cache
before_script:
  # unique hash of required dependencies
  - PACKAGE_HASH=($(md5sum package.json))
  # path to cache file
  - DEPS_CACHE=/tmp/dependencies_${PACKAGE_HASH}.tar.gz
  # Check if cache file exists and if not, create it
  - if [ -f $DEPS_CACHE ];
    then
      tar zxf $DEPS_CACHE;
    else
      npm install --quiet;
      tar zcf - ./node_modules > $DEPS_CACHE;
    fi

stages:
  - build

build:client:
  stage: build
  script:
    - npm run build:client

build:server:
  stage: build
  script:
    - npm run build:server

# test:node:6:
#   image: node:6
#   script:
#     - npm run build:client
#     - npm run build:server
